# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value


services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.blog_repo:
          class: AppBundle\Entity\BlogPostRepository
          factory: "doctrine.orm.entity_manager:getRepository"
          arguments: [AppBundle\Entity\BlogPost]
      app.comment_repo:
          class: AppBundle\Entity\CommentRepository
          factory: ["@doctrine", getRepository]
          arguments:
            - AppBundle\Entity\Comment
      app.blog_manager:
          class: AppBundle\Service\BlogManager
          arguments: ["@app.blog_repo", "@app.comment_repo"]