# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value


services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.blog_repo:
          class: AppBundle\Entity\BlogPostRepository
          factory: ["@doctrine.orm.default_entity_manager",getRepository]
          arguments:
            - AppBundle\Entity\BlogPost
      app.blog_manager:
          class: AppBundle\Service\BlogManager
          arguments: ["@app.blog_repo", "@doctrine.orm.default_entity_manager"]