<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * BlogPostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends EntityRepository
{


    public function findByQuery($query)
    {
        return $this->createQueryBuilder('b')
            ->orWhere(
                'b._title LIKE :query',
                'b._content LIKE :query',
                'b._tags LIKE :query',
                'b._author = :query_exact'
            )
            ->orderBy('b._postedAt', 'DESC')
            ->setParameters([
                'query'=>"%".$query."%",
                'query_exact' => $query
            ])
            ->getQuery()
            ->getResult();
    }

    public function findAllDesc()
    {
       return $this->findBy([],['_postedAt'=>'DESC']);
    }



}
